### ISSUE TITLE
make target=x86-64

### ISSUE THREAD

**Issue by masterzorag** [ps4dev/elfldr#4]
on building build/main.c.o:
...
clang  -c source/main.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude -DDebug  -fPIE -DElfLoaderEmulatePS4Memory -DPayload=0x926400000 -o build/main.c.o

struct sigaction sa;
error: variable has incomplete type 'struct sigaction'
warning: implicit declaration of function 'sigaction' is invalid in C99 [-Wimplicit-function-declaration]

I've added #define _POSIX_C_SOURCE, it seems included but not honored, but I've fixed building by calling:
clang  -c source/main.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude -DDebug  -fPIE -DElfLoaderEmulatePS4Memory -DPayload=0x926400000 -o build/main.c.o -D_POSIX_C_SOURCE
source/main.c:20:9: warning: '_POSIX_C_SOURCE' macro redefined [-Wmacro-redefined]
# define _POSIX_C_SOURCE

<command line>:4:9: note: previous definition is here
# define _POSIX_C_SOURCE 1

1 warning generated.

then, make debug=true target=x86-64 can continue and build fine

**Comment by hitodama** [comment]
Maaan, I am so very sorry. I made this as a last minute change (switching from old style signal to sigaction) and didn't properly verify it. The second time a last minute change annoyed you :( I vow to do better :( I had to run out but wanted to commit ... that never goes well ...

The fix is to define #define _XOPEN_SOURCE :)

I also saw you comment on libusbfat. If you try to build it with libps4 (from ps4dev) you should not need the initializers. If you like I can try to get it to build for you, just ask :)
